version: "3.9"
services:
  my-webhooks:
    image: ghcr.io/yonitlz/my-webhooks:latest
    container_name: "my-webhooks"
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - astro-devlog-mongo
    env_file:
      - my-webhooks/.env
    networks:
      - astro-devlog-network
  astro-devlog:
    image: ghcr.io/yonitlz/temporary-voice-channels-discord-bot:latest
    container_name: "astro-devlog"
    depends_on:
      - astro-devlog-redis
      - astro-devlog-mongo
    env_file:
      - .env
    networks:
      - astro-devlog-network
  astro-devlog-redis:
    image: redis:7.0.4
    container_name: "astro-devlog-redis"
    restart: always
    command: redis-server
    networks:
      - astro-devlog-network
  astro-devlog-mongo:
    image: mongo:4.4.6
    container_name: "astro-devlog-mongo"
    restart: always
    volumes:
      - db-data:/data/db # This is the default location for mongodb data storing
    networks:
      - astro-devlog-network

volumes:
  db-data:

networks:
  astro-devlog-network:
    name: astro-devlog-network
